In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("data/funnel_events_sample.csv")

In [3]:
df

    user_id                step            timestamp
0      U070      signup_started  2026-07-20 04:18:00
1      U026      signup_started  2026-07-20 03:49:00
2      U007        visited_site  2026-07-20 03:32:00
3      U136        visited_site  2026-07-20 03:40:00
4      U018        visited_site  2026-07-20 03:57:00
..      ...                 ...                  ...
537    U197      details_filled  2026-07-20 04:27:00
538    U135  purchase_completed  2026-07-20 04:31:00
539    U100  purchase_completed  2026-07-20 04:37:00
540    U059      email_verified  2026-07-20 04:34:00
541    U159        visited_site  2026-07-20 03:31:00

[542 rows x 3 columns]

In [4]:
df.duplicated().sum()

np.int64(0)

In [5]:
df.isnull().sum()

user_id      0
step         0
timestamp    0
dtype: int64

- No duplicates and null values

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 542 entries, 0 to 541
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   user_id    542 non-null    object
 1   step       542 non-null    object
 2   timestamp  542 non-null    object
dtypes: object(3)
memory usage: 12.8+ KB

In [13]:
df["user_id"] = df["user_id"].astype('string')
df["timestamp"] = pd.to_datetime(df["timestamp"])

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 542 entries, 0 to 541
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   user_id    542 non-null    string
 1   step       542 non-null    object
 2   timestamp  542 non-null    datetime64[ns]
dtypes: datetime64[ns](1), object(1), string(1)
memory usage: 12.8+ KB

In [15]:
df

    user_id                step           timestamp
0      U070      signup_started 2026-07-20 04:18:00
1      U026      signup_started 2026-07-20 03:49:00
2      U007        visited_site 2026-07-20 03:32:00
3      U136        visited_site 2026-07-20 03:40:00
4      U018        visited_site 2026-07-20 03:57:00
..      ...                 ...                 ...
537    U197      details_filled 2026-07-20 04:27:00
538    U135  purchase_completed 2026-07-20 04:31:00
539    U100  purchase_completed 2026-07-20 04:37:00
540    U059      email_verified 2026-07-20 04:34:00
541    U159        visited_site 2026-07-20 03:31:00

[542 rows x 3 columns]